### ISSUE TITLE
When??

### ISSUE THREAD

**Issue by ForBai** [QuantumClient/Renderer#2]
![when??](https://user-images.githubusercontent.com/79467608/126483480-82897188-5f6e-48bf-b54f-8991fe56b77c.png)
when do you add "other stuff"?

**Comment by ChiquitaV2** [comment]
i've been working on it lately, already finished shaders now i just need to finish the rest and clean it up

**Comment by ForBai** [comment]
ok thanks for the answer

**Comment by ForBai** [comment]
ok thanks for the answer
